new_variables:
  pf_mask: awkward.ones_like(Part_E)
  # log_E: np.log(B_E)

preprocess:
  method: manual
  data_fraction: 1.0

inputs:
  pf_points:
    length: 35
    vars:
      - Part_eta
      - Part_phi
    pad_mode: constant
    pad_value: 0

  pf_features:
    length: 35
    vars:
      - Part_E
      - Part_px
      - Part_py
      - Part_pz
    pad_mode: constant
    pad_value: 0

  pf_mask:
    length: 35
    vars:
      - pf_mask

labels:
  type: simple
  value: [B_E, B_px, B_py, B_pz]
  var_funcs: {}

observers:
  - pdg_id
